### ISSUE TITLE
Enhancements to Explore Data endpoint(s) & email template

### ISSUE THREAD

**Issue by FaithDaka** [airqo-platform/AirQo-api#1075]
1. Data endpoint for registering organisations returns a _500_ error. Which endpoint should be used?
![Screenshot (44)](https://user-images.githubusercontent.com/53012890/190729380-092ad856-187f-4046-b382-ddfd698d2080.png)

2. The responding email address should have a user name that defines _AirQo Data_ rather than the name _data_. This is to add professionality to the email responses.
![Screenshot (45)](https://user-images.githubusercontent.com/53012890/190730777-4880e279-f558-4d52-8c4b-7bbecd04778c.jpg)

3. The wording in the email responses requires attention as well. "Once your application is approved, you will receive a confirmation email in this mailbox" reads better.
![Screenshot (46)](https://user-images.githubusercontent.com/53012890/190730154-73b1b468-bb59-4b0a-a9e4-94db1513dbc4.jpg)

**Comment by 123MwanjeMike** [comment]
Hi @FaithDaka, Thanks for making these observations.
I have a few comments to share however.
- Firstly, you are getting the response you are getting for not found is 404 under the hood, I think @Baalmart could share the correct endpoint. This is not an issue with the auth-service or the infrastructure.
- For about the professionalism in data@airqo.net vs airqodata@airqo.net, I think the former is better given that the email already has airqo in it, thus indicating the data is from AirQo. The later has repetition.

cc @Baalmart
