### ISSUE TITLE
Feedback endpoint not working as expected.

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-api#1239]
**What were you trying to achieve?**
I was trying to send feeedback using the feedback endpoint.

**What are the expected results?**
I expected a response status of 200

**What are the received results?**
Received 
```json
{
  "success": true,
  "message": "email not sent",
  "status": 502,
  "errors": 500
}
```

**What are the steps to reproduce the issue?**
Make a post request to
```http
https://api.airqo.net/api/v1/users/feedback
```
Replace email with your email address.

```json
{
  "email": "testing@testing.com",
  "subject": "testing",
  "message": "testing"
}
```

**In what environment did you encounter the issue?**

**Additional context**
Any other information you would like to share?

**Comment by Baalmart** [comment]
Thanks @NoahNsimbe for this.

Let me check it out later today.
