### ISSUE TITLE
Auth & Device registry Hotfixes

### ISSUE THREAD

**Issue by Codebmk** [airqo-platform/AirQo-api#1669]
**Is your feature request related to a problem? Please describe.**
- [ ] Add the network field to user activity logs ie net_name, net_id
- [ ] Requesting data access to a specific organization??
- [ ] Inviting non-airqo users to a network??
- [ ] Users should be able to create new devices to any existing network
- [ ] Handling users that want to register new organisations using gmail, yahoo etc
- [x] Add user details to the site activity logs
- [ ] When an assigned user is deleted, are they entirely deleted from the users list or added to the available users list?
- [x] The assigned users list is missing the user's role_name and role_id that's why it is empty in the assigned users table
- [x] Specify which of the CRUD actions occurred in the logs message and to what(eg device, site, user etc) in the message output under the logs endpoint
- [ ] Is it possible to have the device name/site name/airqloud name etc in the action message? Like what has been acted upon especially for network management related logs
- [x] This successful login message on device registry/auth service etc is confusing (edited) 
- [x] what parameter does this endpoint expect  /users/permissions ? The error says user_id: "the user ID must be an object ID" ...Permissions are a unique entity(and are system created(created by developers) and not user created(external user), they are also not tied to networks). Get permissions are returned as they are. No need for passing in any parameters. The error is new..probably from a new change you introduced??
- [x] Unable to create an "old" AirQloud for Nigeria: something about admin_levels not being recognised.
- [x] the grid information api is missing the visibility field
- [x] the updated_cohort array is empty even though the devices are successfully added when a user assigns devices to a cohort (edite
- [ ] For network or organisation creation, we could have a field which allows someone to input a preferable name for their organisation instead of picking this name from the email address?
- [ ] Add a notification system to alert the Hardware engineers whenever a new Device is deployed. Example: the recent devices from Detroit were deployed and the hardware engineers needed to know about this development. This could fit into the INCENTIVES microservice?
- [ ] There's a small issue with site creation. It doesn't accept sites that already exist even though the site is not belonging to that network.
When I used Jinja's coordinates in a different network, it said the coordinates should be unique even though I created the site in a different network. (edited) 

**THE ONES BELOW ARE PICKED FROM "CLOSED" ISSUES:**
- [ ] Support mobile app users who would like to access the platform using the same credentials. A user with an app account should be able to login to the platform.
- [x] Add Unit Tests for all access control implementations
- [ ] Incorporate role based middleware that checks whether the user making the request has the required role before
- [ ] Are the users added through the Approval process added to any network? Is it even necessary?
- [ ] An opportunity for us to also provide support for deleting Platform accounts.
- [ ] Ability to refresh JWT token without having to login
- [ ] On updating Roles, find out why input validation flags addition of role_name and role_code yet they are not provided in the request. Also, does not flag them if they are provided.
- [ ] Networks can also have profiles with images
- [ ] Handle input validations for GET Events. eg: device_id, etc
- [ ] On the latest measurements endpoint (`/api/v1/devices/events/latest`), Missing network id and visibility field.
- [ ] Filter measurements by network name/id and visibility
- [ ] Unable to create a site with similar coordinates as a site on another network. Says coordinates should be unique.
- [ ] - [ ] as time goes on, we shall consider just returning measurements for public devices only....especially for the case of latest measurements endpoint
- [ ] create a many to many relationship between **AirQlouds** and **Organisations** where
- [x]  Make sure that the user exists when creating a token. At the moment, any MongoID can create a token.
- [ ] Scale the distance to the capital city (Not just Kampala) so that it is international.

**Comment by AnthonyByansi** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace.githubnext.com/airqo-platform/AirQo-api/issues/1669?shareId=e35dfbe2-190a-4873-b420-78954cddff65) saved by @AnthonyByansi using Copilot Workspace v0.22

<details open><summary><b>Topic</b></summary>
<br/>

Is the network field added to user activity logs?

</details>

<details open><summary><b>Before</b></summary>
<br/>

- No, the network field is not added to user activity logs.
- The `network` field is defined in the `activitySchema` in `src/device-registry/models/SiteActivity.js`.
- The `network` field is included in the `toJSON` method of the `activitySchema` in `src/device-registry/models/SiteActivity.js`.
- The `network` field is not utilized in the `deploy`, `recall`, `maintain`, `update`, and `delete` methods in `src/device-registry/controllers/create-activity.js`.
- The `network` field is not included in the response of the `list` method in `src/device-registry/controllers/create-activity.js`.

</details>
<details open><summary><b>After</b></summary>
<br/>

* Yes, the network field is now added to user activity logs.
* The `network` field is defined in the `activitySchema` in `src/device-registry/models/SiteActivity.js`.
* The `network` field is included in the `toJSON` method of the `activitySchema` in `src/device-registry/models/SiteActivity.js`.
* The `network` field is utilized in the `deploy`, `recall`, `maintain`, `update`, and `delete` methods in `src/device-registry/controllers/create-activity.js`.
* The `network` field is included in the response of the `list` method in `src/device-registry/controllers/create-activity.js`.


</details>

<details open><summary><b>Plan</b></summary>
<br/>

* `src/device-registry/controllers/create-activity.js` (CHANGE)
  - Add the `network` field to the `deploy`, `recall`, `maintain`, `bulkAdd`, `bulkUpdate`, `update`, `delete`, and `list` methods
  - Include the `network` field in the response of the `deploy`, `recall`, `maintain`, `bulkAdd`, `bulkUpdate`, `update`, `delete`, and `list` methods
* `src/device-registry/models/SiteActivity.js` (CHANGE)
  - Include the `network` field in the response of the `register`, `list`, `modify`, and `remove` methods

</details>

<details open><summary><b>Sketch of implementation</b></summary>
<br/>

[View the changes](https://copilot-workspace.githubnext.com/airqo-platform/AirQo-api/issues/1669?shareId=e35dfbe2-190a-4873-b420-78954cddff65)

<details open><summary><b>Details</b></summary>
<br/>

Code analyzed at 196c218ebc30f78985794e1a88d13291944ac50d

</details>
