### ISSUE TITLE
Upgrade all GitHub workflow actions currently using node12(deprecated)

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-api#1726]
**What were you trying to achieve?**
Running the repo [workflows](https://github.com/airqo-platform/AirQo-api/tree/staging/.github/workflows)

**What are the expected results?**
Workflows are expected to run without any warnings

**What are the received results?**
Workflows were running with `save-state`  and `set-output` deprecation warnings
![image](https://github.com/airqo-platform/AirQo-api/assets/41787587/e06af50d-90af-4e08-ad3d-3a1686477de3)
![image](https://github.com/airqo-platform/AirQo-api/assets/41787587/e4235a7c-d3b9-4c1f-a5b3-412bff48797a)

**Additional context**
- An example of a GitHub Action workflow run with the `save-state` warning is [here](https://github.com/airqo-platform/AirQo-api/actions/runs/5353495977/jobs/9709444223#step:5:12)
- An example of a GitHub Action workflow run with the `set-output` warning is [here](https://github.com/airqo-platform/AirQo-api/actions/runs/5353495977/jobs/9709444223#step:5:106)
- [This article](https://hynek.me/til/set-output-deprecation-github-actions/) may provide some context on this.
- Sample places where the GitHub actions to update are used include:
  - https://github.com/airqo-platform/AirQo-api/blob/ec9b7960c71b3da2a4f65e7a5a166fb074bf7d6f/.github/workflows/remove-deploy-previews.yml#L18
  - https://github.com/airqo-platform/AirQo-api/blob/ec9b7960c71b3da2a4f65e7a5a166fb074bf7d6f/.github/workflows/deploy-apis-to-staging.yml#L393
- You can also update all other GitHub actions you notice to be outdated apart from `Wandalen/wretry.action@v1.0.36`
- The ideal solution addresses this issue in [all the workflows](https://github.com/airqo-platform/AirQo-api/tree/staging/.github/workflows)

**Comment by Baalmart** [comment]
@123MwanjeMike , 

- Aren't these Github Actions upgrades the ones which brought us problems sometime back? The time when all PRs refused to be deployed after merge
- Anyway, just requesting that we apply some caution as we go about this.
