### ISSUE TITLE
Device Registry add device maintenance logs

### ISSUE THREAD

**Issue by ja-odur** [airqo-platform/AirQo-api#190]
Creating new logs with the endpoint `POST http://34.78.78.202:31002/api/v1/devices/ts/activity?type=maintain&tenant=airqo`
Sample data:
{
    "deviceName": "aq_33",
    "description": "preventive",
    "location": "loc_33",
    "tags": ["Dust blowing and sensor cleaning", "Site update check", "Device equipment check"],
    "date": "2020-10-25T16:09:24.611Z"
}

Returns this error message:
{
    "success": false,
    "message": "unable to create activity",
    "error": "tenant is not defined"
}

**Comment by Baalmart** [comment]
Hi @ja-odur 
Looks like it works well with the latest staging (**localhost**) for **device-registry**, we just need to re-deploy accordingly.
cc: @danielogen 

![image](https://user-images.githubusercontent.com/1590213/97158719-e469d980-178a-11eb-97e1-d6c5a1ce22fb.png)

**Comment by danielogen** [comment]
This was done sometime back cc: @Baalmart and @ja-odur

**Comment by Baalmart** [comment]
Looks like we are also good here. Thanks @danielogen
