### ISSUE TITLE
 server instance pool was destroyed

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#217]
**What were you trying to achieve?**
Login to the platform

**What are the expected results?**
Successful login

**What are the received results?**
Runtime error which occurs unexpectedly. Hard to reproduce. Error message: "MongoError: server instance pool was destroyed".
Only removed after application restart

**What are the steps to reproduce the issue?**
Hard to reproduce it, just happens.
But research online shows that this error is typical when an insert/update/remove is executed (under the belief that the DB connection is still up), but the connection is determined to be down before the result is received. This client error only happens after the server loses it's db connection.

**In what environment did you encounter the issue?**
node v12.18.1

**Additional context**
It might be something at application level.
More details can be found [here](https://stackoverflow.com/questions/49429462/mongoerror-server-instance-pool-was-destroyed)
Another narration is [here](https://github.com/meteor/meteor/issues/7822)

**Comment by danielogen** [comment]
[PLAT-307] - testing JIRA <> GitHub Integration. PLEASE IGNORE!!
