### ISSUE TITLE
testing JIRA and Git

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#264]
**What were you trying to achieve?**
testing......
[PLAT-386] is the issue on JIRA

[PLAT-386]: https://airqoteam.atlassian.net/browse/PLAT-386

**Comment by danielogen** [comment]
TEST 1 successful [PLAT-386]

**Comment by danielogen** [comment]
TEST 2 [PLAT-386] #done testing jira task transition
