### ISSUE TITLE
Updating maintenance logs does not update `maintenanceType` field

### ISSUE THREAD

**Issue by ja-odur** [airqo-platform/AirQo-api#289]
**What were you trying to achieve?**
How to replicate the issue
Hit the update log endpont `PUT http://34.78.78.202:31002/api/v1/devices/ts/activity/update?id=604c88fb3fc26c002bea5d7d&tenant=airqo`

sample data
```
{
    "description": "new description",
    "maintenanceType": "custom new"
}
```

**What are the expected results?**
updated maintenance log (including the maintenanceType field but it's not updated)

**What are the received results?**
![image](https://user-images.githubusercontent.com/39955305/111194282-18278d80-85cc-11eb-93b5-8cbb61c9d5ab.png)

**Comment by Baalmart** [comment]
I guess this was resolved accordingly, please see attached screenshot.

![image](https://user-images.githubusercontent.com/1590213/111380343-459c3600-86b5-11eb-827d-922809def90f.png)
