### ISSUE TITLE
Integrating feedback mechanism/endpoint

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#328]
**Is your feature request related to a problem? Please describe.**
Integrating feedback mechanism/endpoint into the platform

**Describe the solution you'd like**

- An endpoint
- Utilising some already existing tools like JIRA, mailchimp

**Describe alternatives you've considered**
- An endpoint
- Utilising some already existing tools like JIRA, mailchimp

**Additional context**
To integrate these feedback mechanisms into a microservice of sorts and also integrate them as Kafka topics accordingly.

**Comment by NoahNsimbe** [comment]
@Baalmart which microservice should I use
