### ISSUE TITLE
Getting recent events at mid-night returns an empty array

### ISSUE THREAD

**Issue by ja-odur** [airqo-platform/AirQo-api#331]
**What were you trying to achieve?**
Accessing the recent events of every devices at the start of the day (i.e. between mid-night and about 2am) returns an empty array.

**What are the expected results?**
Getting recent events should not return an empty array (should not depend on the day) unless there are completely no records in the events collection

**What are the received results?**

**What are the steps to reproduce the issue?**
Query this `GET` endpoint `http://localhost:3000/api/v1/devices/events?tenant=kcca&recent=true&startTime={}&endTime={}&limit=100` at mid-night. Remember to replace the `startTime` and `endTime` with the right date corresponding to the mid-night date.

**In what environment did you encounter the issue?**

**Additional context**
Any other information you would like to share?

**Comment by Baalmart** [comment]
This was resolved. cc: @ja-odur
