### ISSUE TITLE
Device Registry doesnt return Airqo devices 

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-api#337]
**What were you trying to achieve?**
Get Airqo devices

**What are the expected results?**
A JSON body containing Airqo devices or an appropriate message incase the devices are not available

**What are the received results?**
>Status: 200 OK
> {
>     "success": true,
>     "message": "Devices fetched successfully"
> }

**What are the steps to reproduce the issue?**
Attempt to get Airqo devices while the db is off/down

**In what environment did you encounter the issue?**

**Additional context**
Any other information you would like to share?
Response needs to be modified to reflect the situation. If the devices are not available then the User needs to be informed other than saying  `"Devices fetched successfully"` and returning none.

**Comment by Baalmart** [comment]
This has been resolved by a merged [PR-344](https://github.com/airqo-platform/AirQo-api/pull/344)
