### ISSUE TITLE
Device creation naming convention

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#353]
**Is your feature request related to a problem? Please describe.**
The hardware team currently using the following naming convention many times:

-  AIRQO WBI UNIT ACTIVE
- AIQRO-WB6 UNIT ACTIVE

**Describe the solution you'd like**
The device name should reflect the current scenario that the hardware team uses. This means that these names should be very descriptive.

**Describe alternatives you've considered**
- The device name will no longer be unique.
- We shall have to use the channel ID as the unique ID for each Device. To have a generic structure, we shall have to consider using a more generic name like `deviceCode` as the unique field in the database
- We can also just use the Mongo DB IDs as the unique identifiers when querying accordingly.

**Additional context**
This is in relation to feedback where the hardware team does not relate with the naming convention we have. The current one is aq_<NUMBER>. Also the hardware team uses some characters of these names in some other monitoring systems---their implementations look out for some parts of the device names in order to compute a device status.

**Comment by easybeinggreen** [comment]
I am concerned about the ability to RENAME a device. The device name should be unique and permanent so we can alwasy follow a device when conducting analysis. If device names are changing this is a risk. So perhaps a chance to name it on creation but not rename during its lifetime.
Name of device should not be dependent on site / location

As mentioned in meeting channel ID should relate to one and only one device. The same channel ID cannot be used for a new device in the same location. This will make analysis extremely difficult and collocation impossible.

Is the naming issue a blocker to achieving any other goals or a preference? Interested to hear
The needs of analysts need to be considered alongside he needs of hardware team. I am nervous about changing this at this stage. There are many other higher priority tasks namely getting the data out there.

**Comment by Baalmart** [comment]
> I am concerned about the ability to RENAME a device. The device name should be unique and permanent so we can alwasy follow a device when conducting analysis. If device names are changing this is a risk. So perhaps a chance to name it on creation but not rename during its lifetime.
> Name of device should not be dependent on site / location
> 
> As mentioned in meeting channel ID should relate to one and only one device. The same channel ID cannot be used for a new device in the same location. This will make analysis extremely difficult and collocation impossible.
> 
> Is the naming issue a blocker to achieving any other goals or a preference? Interested to hear
> The needs of analysts need to be considered alongside he needs of hardware team. I am nervous about changing this at this stage. There are many other higher priority tasks namely getting the data out there.

Thanks @easybeinggreen , good points you have raised. Thanks, much appreciated! :)  I will share some quick thoughts alongside your thoughts:

- According to the hardware team (Joel), the naming convention issue negatively affects their user experience (UX). And a bad UX reduces their adoption rate/speed of the platform. If they (hardware team) experience/share any UX issues and we do not address them, they will eventually minimise their interactions with the tool which will end up frustrating all stakeholders involved. I guess approaching UI/UX development from the angle of data analysis needs can bring about a bad UX/UI. We should be able to get all the data we need without directly translating data analysis formats/needs on the UI/frontend of the system - this issue is a great example that could also be borrowed for other sections like `site registry`.
- I also like the point of allowing them to use their own device naming conventions but prevent them from renaming it during its lifetime >> sounds good and I guess it will not negatively affect their UX in the process.
- Unless I am missing something, this somehow "uncomfortable" change does not prevent/stop data from getting out there. One can easily retrieve data using other unique fields like `channel IDs`, `mongoDB IDs` or even `device Codes`.
- Could you shed more light on this statement? >>> "The same channel ID cannot be used for a new device in the same location". The statement makes a lot of sense and it is very relatable, I am just not sure how it connects with this issue. How does this proposed change bring about the utilisation of the same channel ID in the same location/site? How does the location/site come into the picture?
- As for "name of device should be unique and permanent"......the channel ID, mongoDB ID, clarity deviceCode can also be used for analysis since they are also unique and permanent. Could there be any foreseen challenge in using other already existing unique fields (channel ID, deviceCode and mongoDB IDs) for analysis? Could it be that the analysts want the unique identifiers to be more descriptive in nature?
- On a side note, this naming convention issue could also be one of the "invisible" blockers for site registry. What if it also negatively affects the user experience of the frontend users? Using system generated unique IDs for data retrieval could somehow ensure that the analysts get the data they want without negatively affecting the UX of the system by the UI users (Joel and rest of hardware team) hence a win-win of sorts.

**Comment by Baalmart** [comment]
This was adddressed.
