### ISSUE TITLE
fetch Events by frequency

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#357]
**Is your feature request related to a problem? Please describe.**
There is a need to fetch device measurements using the frequency field. Frequency is the duration/average of the measurements done. The rate at which the measurements were sampled. Can be:

- hour
- minutes
- raw
- day

**Describe the solution you'd like**
I would like to be able to fetch device measurements by frequency tab

**Describe alternatives you've considered**
None

**Additional context**
 None

**Comment by NoahNsimbe** [comment]
We need to agree on the accepted values for frequency. `daily vs day`, `hourly vs hour`, `minutes vs minute `etc. For KCCA we are using `hourly` #363 is using `hours` and here we have stated `hour`

**Comment by Baalmart** [comment]
resolved
