### ISSUE TITLE
system somehow crushes whenever user queries devices by device name

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#388]
**What were you trying to achieve?**
Use the Get devices endpoint to search for details of a specific device

**What are the expected results?**
Just return the results/details of that specific device

**What are the received results?**
One the localhost, the system returns the results without an issue. However, the system becomes unresponsive when the operation targets the cloud servers/DBs in either staging/production.

**What are the steps to reproduce the issue?**
Just utilise the Get Devices endpoint in production/staging environment and using the `name` query parameter accordingly.
[GET] http://localhost:3000/api/v1/devices?tenant=airqo&name={DEVICE_NAME}
While at it, try to run in staging/production. And in case anything bad happens, please follow up with the DevOps engineer to ensure that the respective cluster is either restored/functional.

**In what environment did you encounter the issue?**
N/A

**Additional context**
This behaviour can also be seen in the frontend when querying for specific device information. Happened when I was checking out device details for device 6A.

**Comment by danielogen** [comment]
> [http://localhost:3000/api/v1/devices?tenant=airqo&name={DEVICE_NAME}](http://localhost:3000/api/v1/devices?tenant=airqo&name=%7BDEVICE_NAME%7D)

Hi @Baalmart, looks like this was related to a cluster node that was not operational. This has been resolved and the endpoint seems to be working well.
![Screenshot 2021-05-22 at 13 38 19](https://user-images.githubusercontent.com/15224992/119223624-254c8580-bb03-11eb-8c7c-1cf2704802f0.png)

**Comment by Baalmart** [comment]
Okay, shall close this for now. Thanks @danielogen .
