### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-api#395]
**What were you trying to achieve?**
Consume device registry endpoints on the mobile app and postman

**What are the expected results?**
Devices measurements, Devices etc

**What are the received results?**
SSL error
![postman](https://user-images.githubusercontent.com/37845280/119795777-75e82800-bee1-11eb-940c-3757ea1c0c31.png)
![flutter](https://user-images.githubusercontent.com/37845280/119795795-7a144580-bee1-11eb-991b-f19b61a91e42.png)

**What are the steps to reproduce the issue?**
Consume any device registry endpoint using https on postman or run the mobile app using https

**In what environment did you encounter the issue?**
 - Android Version 8.1
 - Postman

**Additional context**
None

**Comment by Baalmart** [comment]
Hi @NoahNsimbe 
- You could try to use: http instead of https
- Alternatively, just disable SSL Verification in postman.
cc: @danielogen

**Comment by NoahNsimbe** [comment]
> Hi @NoahNsimbe
> 
> * You could try to use: http instead of https
> * Alternatively, just disable SSL Verification in postman.
>   cc: @danielogen

Alright, but for release builds it would be better/recommended if we used https, https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android ...

**Comment by danielogen** [comment]
Hi @here: 
This issue is now resolved. You can try testing the endings on POSTMAN without disabling SSL verification. Thanks!
cc: @Baalmart, @ja-odur, @Priscilla-AL, @NoahNsimbe

**Comment by NoahNsimbe** [comment]
> Hi @here:
> This issue is now resolved. You can try testing the endings on POSTMAN without disabling SSL verification. Thanks!
> cc: @Baalmart, @ja-odur, @sserurich, @NoahNsimbe

Works well......thanks @danielogen

**Comment by Baalmart** [comment]
Thanks for the confirmation @NoahNsimbe , so I am going ahead to close. cc: @danielogen
