### ISSUE TITLE
Revise the frequency logic for device registry

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-api#425]
**Is your feature request related to a problem? Please describe.**
Device registry keeps rejecting measurements claiming they have already been inserted, but when you query for the measurements they don't exist.

**Describe the solution you'd like**
Revise the logic for inserting device measurements, especially the frequency logic, below are key points that I think we should consider. 

- If frequency is **daily**, first format the measurement's **date-time** to **YYYY:MM:ddT00:00:00.000Z**. Note that the time has been replaced with **00:00:00.000** since it's not need to perform checks for  frequency of **daily**, only the **date** is required. Now proceed to make sure that **device**, **frequency** and **date-time** are unique.

- If frequency is **hourly**, first format the measurement's **date-time** to **YYYY:MM:ddThh:00:00.000Z**. Note that the time has been replaced with **hh:00:00.000** since only **hourly** is needed to perform the checks, **seconds**, **minutes**, **milliseconds** are not needed. Now proceed to make sure that **device**, **frequency** and **date-time** are unique.

- If frequency is **raw** or not defined, first format the measurement's **date-time** to **YYYY:MM:ddThh:mm:ss.SSSZ** then proceed to make sure that **device**, **frequency** and **date-time** are unique. 

***Suggested date-time formats for the frequencies***
daily : **YYYY:MM:ddT00:00:00.000Z**
hourly: **YYYY:MM:ddThh:00:00.000Z**
raw: **YYYY:MM:ddThh:mm:ss.SSSZ**

**_For insertions without the frequency field, the default frequency value should be **raw**_**

**Describe alternatives you've considered**
None

**Additional context**
This issue may be a blocker to #426

**Comment by Baalmart** [comment]
Hi @NoahNsimbe 
With the new [PR-499](https://github.com/airqo-platform/AirQo-api/pull/449), these recommendations might not be necessary unless otherwise. Awaiting feedback on this new [PR-499](https://github.com/airqo-platform/AirQo-api/pull/449)
