### ISSUE TITLE
Kcca Freqency Measurements

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-api#426]
**What were you trying to achieve?**
User wants to access kcca device measurements averaged by **hour** and **day**

**What are the expected results?**
Device measurements with a frequency or either **day** or **hour** depending on the query parameters

**What are the received results?**
The number of returned device measurements are less than what is expected.

**What are the steps to reproduce the issue?**
Perform get a request on the [get events endpoint](https://docs.airqo.net/airqo-platform-api/device-registry#get-events), specify **frequency=day** or **frequency=hour** for example 
https://staging-platform.airqo.net/api/v1/devices/events?tenant=kcca&startTime=2021-01-01T00:00:00Z&recent=no&frequency=day
https://staging-platform.airqo.net/api/v1/devices/events?tenant=kcca&startTime=2021-01-01T00:00:00Z&recent=no&frequency=hour

**In what environment did you encounter the issue?**
 - Postman

**Additional context**
It would be better to have #425 resolved before the averaged kcca measurements are sent to device registry for storage

**Comment by Baalmart** [comment]
Hi @NoahNsimbe , a fix for this has been raised in a new [PR-499](https://github.com/airqo-platform/AirQo-api/pull/449)
