### ISSUE TITLE
k8s cluster workflow for different development stages

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#429]
**Is your feature request related to a problem? Please describe.**
It could be tricky for some members to practice our workflow at the infrastructure level. At the moment, not all members on the team are able to easily deploy things for testing purposes --partly due to the current structure of our infrastructure workflow.

**Describe the solution you'd like**
A possibility for us to have development and scratch clusters. Each of one of these two clusters can have different namespaces for different purposes.

**Describe alternatives you've considered**

- Development Cluster

> frontend namespace
> storage namespace
> backend namespace

- Scratch Cluster

> default namespace
> auxiliary namespace

**Additional context**

- So we could also have a production cluster accordingly.
- What are the cost implications of these suggestions?
- What are the workload implications of this suggestion? Does it increase the workload of DevOps?
- Does this suggestion improve our efficiency?
- At the same time, all team members could explore switching contexts on their machines so that they can switch between various clusters with much ease. Using aliases in the SHELL environment could come in handy, example: kubectly could just have an alias of k.

**Comment by Baalmart** [comment]
Hi @123MwanjeMike , any quick thoughts on this suggestion/issue? cc: @NoahNsimbe

**Comment by 123MwanjeMike** [comment]
> Hi @123MwanjeMike , any quick thoughts on this suggestion/issue? cc: @NoahNsimbe

I think we already have a development namespace on staging specifically to address this. Creating of 2 additional clusters will definitely have a huge cost implication.

**Comment by Baalmart** [comment]
@NoahNsimbe / @123MwanjeMike 
I am reopening this issue since I still feel that it needs further exploration, despite the cost implications Mike raised.
