### ISSUE TITLE
correct field in Sites schema

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#492]
**What were you trying to achieve?**
View site details...

**What are the expected results?**
all keys/attributes to be named correctly...

**What are the received results?**
One attribute needs correction.

**What are the steps to reproduce the issue?**
 Current one is `distance_to_nearest_residential_area` but it is supposed to be `distance_to_nearest_residential_road`

**Additional context**
Any other information you would like to share?

**Comment by danielogen** [comment]
Setup a working meeting to implement the changes on both frontend and backend.

**Comment by Baalmart** [comment]
this was addressed.
