### ISSUE TITLE
Deleting device photos throws an error

### ISSUE THREAD

**Issue by ja-odur** [airqo-platform/AirQo-api#590]
**What were you trying to achieve?**
When you try to delete a device, you get a server error. Check the screenshot for details

![image](https://user-images.githubusercontent.com/39955305/132986269-f9cd94ac-f228-4e9c-bdac-a36fd147c35d.png)

**What are the steps to reproduce the issue?**
On staging (NetManager), navigate to the `aq_g513` photos section and try to delete a photo.

**Comment by Baalmart** [comment]
@ja-odur Thanks for catching this, Addressed in [this PR](https://github.com/airqo-platform/AirQo-api/pull/600)

**Comment by Baalmart** [comment]
Hi @ja-odur , please confirm status of this.
