### ISSUE TITLE
Using Istio to monitor, control, secure and connnect microservices

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#592]
**Is your feature request related to a problem? Please describe.**
Example: https://kai-waehner.medium.com/streaming-microservices-with-apache-kafka-kubernetes-and-service-mesh-envoy-istio-linkerd-d6c82049edee

**Describe the solution you'd like**
Using Istio to monitor, control, secure and connnect microservices

**Describe alternatives you've considered**
N/A

**Additional context**
From a JIRA card

**Comment by wmorgan** [comment]
I hope you also consider Linkerd. Should be significantly faster and lighter than Istio.
