### ISSUE TITLE
Optimising the multi-hop approach

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-api#595]
**Is your feature request related to a problem? Please describe.**
The calibration microservice is to be updated to support improve “multi-hop” ML. This is causing size / performance issues which must be addressed.

**Describe the solution you'd like**
Currently looking into including dataprocessing.py into the module this is based on Make simple calibration a package by bobturneruk · Pull Request #11 · airqo-platform/AirQo-modules This is needed to update the pickle containing a dictionary linking physical locations of sensors. Ultimately, the information in this pickle will be best stored in a database of some kind.

**Describe alternatives you've considered**
Related Multi hop by Priscilla-AL · Pull Request #345 · airqo-platform/AirQo-api 

**Additional context**
Picked from a closed JIRA issue.

**Comment by bobturneruk** [comment]
The related PR needs help from @Priscilla-AL / @danielogen, I think (https://github.com/airqo-platform/AirQo-api/pull/345#issuecomment-896754967). Unless something has changed and I need to try it again?

**Comment by Baalmart** [comment]
> The related PR needs help from @Priscilla-AL / @danielogen, I think ([#345 (comment)](https://github.com/airqo-platform/AirQo-api/pull/345#issuecomment-896754967)). Unless something has changed and I need to try it again?

Cool, thanks @bobturneruk .... I guess we shall wait for their feedback on that PR.
