### ISSUE TITLE
nextMaintenance field Data Type

### ISSUE THREAD

**Issue by noahnsimbe** [airqo-platform/AirQo-api#608]
**What were you trying to achieve?**
I was trying to seralize data from the AirQo API

**What are the expected results?**
I expected all fields to have a constant data type or at most 2 data types 

**What are the received results?**
The `nextMaintenance` field had about 3 data types i.e `null`, `date` and `json object`

<img width="963" alt="Screenshot 2021-09-26 at 22 18 25" src="https://user-images.githubusercontent.com/37845280/134821640-b09292e3-dcaf-4fee-8756-1afe1f16daaa.png">

**What are the steps to reproduce the issue?**
Query for devices on the production environment and compare the different values for `nextMaintenance` 

**In what environment did you encounter the issue?**
 - Chrome Browser

**Additional context**
Any other information you would like to share?

#236

**Comment by Baalmart** [comment]
Hi @NoahNsimbe , just started an email thread about this issue. In the same email thread, I have identified devices whose next maintenance dates are missing. After investigations, we shoud be able to tell what caused the issue and make appropriate corrections accordingly.
