### ISSUE TITLE
Add style guides and linters to the codebase

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-api#748]
**Is your feature request related to a problem? Please describe.**
It's frustrating to have to manually format the code and difficult to keep it consistent.

**Describe the solution you'd like**
Adding linters that follow a consistent style guide

**Describe alternatives you've considered**
-None

**Additional context**
We could decide on which style guide to follow ([Airbnb](https://github.com/airbnb/javascript), [Google](https://google.github.io/styleguide/), etc)

**Comment by NoahNsimbe** [comment]
@123MwanjeMike I recommend Black. I have used it for format code for the airflow utility functions. https://github.com/airqo-platform/AirQo-api/tree/staging/src/airflow/airflow_utils

**Comment by 123MwanjeMike** [comment]
> @123MwanjeMike I recommend Black. I have used it to format the code in airflow utility functions. https://github.com/airqo-platform/AirQo-api/tree/staging/src/airflow/airflow_utils

Thanks @NoahNsimbe. Black looks awesome. Will use it for the python code bases
