### ISSUE TITLE
Support for decrypting keys for multiple devices

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-api#973]
**Is your feature request related to a problem? Please describe.**
It's time consuming to call the same endpoint for every device (177 devices) whose read key needs to be decrypted.

**Describe the solution you'd like**
Ability to decrypt multiple read keys in one API call by specifying encrypted keys and corresponding device number. See attached a screenshot of the proposed solution.

**Describe alternatives you've considered**
None

**Additional context**
<img width="593" alt="Screenshot 2022-08-09 at 20 04 34" src="https://user-images.githubusercontent.com/37845280/183713403-2e38f635-fcb0-43f0-9246-a061c2f7e7d0.png">

**Comment by NoahNsimbe** [comment]
Hi @Baalmart. Will this issue be addressed?

**Comment by Baalmart** [comment]
> Hi @Baalmart. Will this issue be addressed?

Yes @NoahNsimbe , this issue has been addressed by [this PR](https://github.com/airqo-platform/AirQo-api/pull/1074).

Apologies for the late response to this.

**Comment by Baalmart** [comment]
Hi @NoahNsimbe , please review the status of this issue. Thanks.
